const TERMS = [
  {t:"2FA",d:"Two-Factor Authentication — a subset of MFA requiring exactly two verification factors. Often a password plus a one-time code.",cat:"general"},
  {t:"3DES",d:"Triple Data Encryption Standard — applies DES encryption three times to each block. More secure than DES but slower; largely replaced by AES.",cat:"general"},
  {t:"AAA",d:"Authentication, Authorisation, and Accounting — the three pillars of access control: verifying who you are, what you can do, and logging what you did.",cat:"general"},
  {t:"ACL",d:"Access Control List — a set of rules that defines which users or systems are allowed or denied access to a resource.",cat:"arch"},
  {t:"AES",d:"Advanced Encryption Standard — the most widely used symmetric encryption algorithm today. Comes in 128, 192, or 256-bit key sizes.",cat:"general"},
  {t:"APT",d:"Advanced Persistent Threat — a prolonged, targeted cyberattack where an attacker gains and maintains unauthorised access to a network, often for espionage.",cat:"threats"},
  {t:"ARP",d:"Address Resolution Protocol — translates IP addresses to MAC addresses on a local network. Can be exploited in ARP poisoning attacks.",cat:"threats"},
  {t:"AUP",d:"Acceptable Use Policy — a document that defines how employees or users are permitted to use company technology and networks.",cat:"gov"},
  {t:"BCP",d:"Business Continuity Plan — a plan that outlines how an organisation will continue operating during and after a major disruption or disaster.",cat:"gov"},
  {t:"BIA",d:"Business Impact Analysis — a process that identifies the effects of disruption on business functions, used to prioritise recovery efforts.",cat:"gov"},
  {t:"Botnet",d:"A network of infected computers controlled remotely by an attacker, often used to launch DDoS attacks or send spam.",cat:"threats"},
  {t:"BYOD",d:"Bring Your Own Device — a policy allowing employees to use personal devices for work, which introduces additional security risks.",cat:"gov"},
  {t:"CA",d:"Certificate Authority — a trusted organisation that issues digital certificates used to verify identities online (e.g. HTTPS websites).",cat:"general"},
  {t:"CAPTCHA",d:"Completely Automated Public Turing test to tell Computers and Humans Apart — a challenge-response test to prevent automated bots from accessing systems.",cat:"general"},
  {t:"CIA triad",d:"Confidentiality, Integrity, and Availability — the three core goals of information security that all security controls aim to protect.",cat:"general"},
  {t:"CISM",d:"Certified Information Security Manager — an advanced certification for security managers focused on strategy and governance.",cat:"general"},
  {t:"CISSP",d:"Certified Information Systems Security Professional — a prestigious advanced certification covering eight security domains, requiring 5 years' experience.",cat:"general"},
  {t:"CRL",d:"Certificate Revocation List — a list published by a CA of digital certificates that have been revoked and should no longer be trusted.",cat:"general"},
  {t:"CSP",d:"Cloud Service Provider — a company that offers cloud computing resources (e.g. AWS, Azure, Google Cloud).",cat:"arch"},
  {t:"CTI",d:"Cyber Threat Intelligence — information about current or potential attacks that helps organisations defend themselves proactively.",cat:"ops"},
  {t:"CVE",d:"Common Vulnerabilities and Exposures — a public database of known security vulnerabilities, each with a unique ID (e.g. CVE-2024-1234).",cat:"threats"},
  {t:"CVSS",d:"Common Vulnerability Scoring System — a standardised way to rate the severity of security vulnerabilities on a scale of 0 to 10.",cat:"threats"},
  {t:"DDoS",d:"Distributed Denial of Service — an attack where many computers flood a target with traffic to make it unavailable. Harder to stop than a standard DoS.",cat:"threats"},
  {t:"DEP",d:"Data Execution Prevention — a security feature that prevents code from running in memory regions designated only for data.",cat:"arch"},
  {t:"DES",d:"Data Encryption Standard — an older symmetric encryption algorithm now considered insecure due to its short 56-bit key length.",cat:"general"},
  {t:"DHCP",d:"Dynamic Host Configuration Protocol — automatically assigns IP addresses to devices on a network.",cat:"arch"},
  {t:"DLP",d:"Data Loss Prevention — tools and policies that detect and prevent sensitive data from being sent outside an organisation.",cat:"ops"},
  {t:"DMZ",d:"Demilitarised Zone — a network segment between the internal network and the internet, typically hosting public-facing servers like web servers.",cat:"arch"},
  {t:"DNS",d:"Domain Name System — translates human-readable domain names (like google.com) into IP addresses that computers use.",cat:"arch"},
  {t:"DNS poisoning",d:"Also called DNS spoofing — an attack where false DNS records are inserted to redirect users to malicious websites.",cat:"threats"},
  {t:"DoS",d:"Denial of Service — an attack that floods a system with requests to make it unavailable to legitimate users.",cat:"threats"},
  {t:"DRP",d:"Disaster Recovery Plan — a documented plan for restoring IT systems and data after a major incident.",cat:"gov"},
  {t:"EAP",d:"Extensible Authentication Protocol — a framework used in wireless networks that supports multiple authentication methods.",cat:"arch"},
  {t:"EDR",d:"Endpoint Detection and Response — security software that continuously monitors endpoints for suspicious activity and helps respond to threats.",cat:"ops"},
  {t:"Evil twin",d:"A rogue Wi-Fi access point that mimics a legitimate one to intercept traffic from users who connect to it.",cat:"threats"},
  {t:"FDE",d:"Full Disk Encryption — encrypts all data on a storage device so it cannot be read without the correct key. BitLocker is a common example.",cat:"general"},
  {t:"FIDO",d:"Fast Identity Online — a set of open standards for passwordless authentication using biometrics or hardware tokens.",cat:"general"},
  {t:"FIM",d:"File Integrity Monitoring — a tool that detects unauthorised changes to critical system files.",cat:"ops"},
  {t:"FTP",d:"File Transfer Protocol — used to transfer files between computers. Sends data in plain text; SFTP or FTPS are the secure alternatives.",cat:"arch"},
  {t:"Fuzzing",d:"A testing technique that sends random or unexpected data to a program to find crashes or security vulnerabilities.",cat:"ops"},
  {t:"GDPR",d:"General Data Protection Regulation — EU law governing how organisations collect, store, and use personal data of EU citizens.",cat:"gov"},
  {t:"GRC",d:"Governance, Risk, and Compliance — the framework organisations use to manage policies, assess risk, and meet regulatory requirements.",cat:"gov"},
  {t:"Hashing",d:"A one-way function that converts data into a fixed-length string. Used to verify integrity — cannot be reversed to get the original data.",cat:"general"},
  {t:"HIDS",d:"Host-based Intrusion Detection System — monitors a single device for suspicious activity or policy violations.",cat:"ops"},
  {t:"HIPAA",d:"Health Insurance Portability and Accountability Act — US law protecting the privacy of patient health information.",cat:"gov"},
  {t:"Honeypot",d:"A decoy system designed to attract attackers, allowing security teams to study their techniques without risking real systems.",cat:"ops"},
  {t:"HOTP",d:"HMAC-based One-Time Password — a one-time password generated using a counter. Used in hardware tokens like RSA SecurID.",cat:"general"},
  {t:"HTTP",d:"Hypertext Transfer Protocol — the foundation of web communication. Sends data in plain text; should be replaced by HTTPS.",cat:"arch"},
  {t:"HTTPS",d:"HTTP Secure — HTTP with SSL/TLS encryption. Protects data in transit between your browser and a website.",cat:"arch"},
  {t:"IaaS",d:"Infrastructure as a Service — cloud model where you rent virtualised hardware and manage everything above the OS yourself.",cat:"arch"},
  {t:"IAM",d:"Identity and Access Management — systems and policies that control who can access what resources within an organisation.",cat:"general"},
  {t:"IDS",d:"Intrusion Detection System — monitors network or system activity for suspicious behaviour and generates alerts. Detects but does not block.",cat:"ops"},
  {t:"IoC",d:"Indicator of Compromise — evidence that a system has been breached, such as unusual outbound traffic or unexpected file changes.",cat:"ops"},
  {t:"IoT",d:"Internet of Things — physical devices connected to the internet, often with poor built-in security.",cat:"arch"},
  {t:"IPS",d:"Intrusion Prevention System — like an IDS but can also actively block suspicious traffic, not just alert on it.",cat:"ops"},
  {t:"IPSec",d:"Internet Protocol Security — a suite of protocols that encrypts and authenticates IP communications at the network layer. Used in VPNs.",cat:"arch"},
  {t:"ISO 27001",d:"An international standard for information security management systems (ISMS) defining best practices for protecting sensitive data.",cat:"gov"},
  {t:"IV",d:"Initialisation Vector — a random value used in encryption to ensure the same plaintext produces different ciphertext each time.",cat:"general"},
  {t:"Kerberos",d:"An authentication protocol used in Windows Active Directory that uses encrypted tickets to allow single sign-on across a network.",cat:"general"},
  {t:"Keylogger",d:"Malware or hardware device that secretly records keystrokes to capture passwords and sensitive data.",cat:"threats"},
  {t:"KRI",d:"Key Risk Indicator — a metric used to signal that risk is approaching or exceeding an acceptable threshold.",cat:"gov"},
  {t:"LDAP",d:"Lightweight Directory Access Protocol — used to access and manage directory information like user accounts on a network.",cat:"arch"},
  {t:"MAC",d:"Mandatory Access Control — an access control model where the OS enforces access policies based on security labels.",cat:"general"},
  {t:"MAC address",d:"Media Access Control address — a unique hardware identifier assigned to a network interface card (NIC).",cat:"arch"},
  {t:"MDM",d:"Mobile Device Management — software used to remotely manage, monitor, and secure mobile devices in an organisation.",cat:"ops"},
  {t:"MFA",d:"Multi-Factor Authentication — requires two or more verification factors: something you know, have, or are.",cat:"general"},
  {t:"MITM",d:"Man-in-the-Middle — now called on-path attack. The attacker secretly intercepts and alters communication between two parties.",cat:"threats"},
  {t:"NAC",d:"Network Access Control — a system that enforces security policies on devices before allowing them to connect to a network.",cat:"arch"},
  {t:"NAT",d:"Network Address Translation — maps private IP addresses to a public IP, allowing multiple devices to share a single internet connection.",cat:"arch"},
  {t:"NDA",d:"Non-Disclosure Agreement — a legal contract preventing parties from sharing confidential information.",cat:"gov"},
  {t:"NIDS",d:"Network-based Intrusion Detection System — monitors network traffic for suspicious patterns across the whole network.",cat:"ops"},
  {t:"NIST",d:"National Institute of Standards and Technology — US government body that publishes widely-used cybersecurity frameworks and guidelines.",cat:"gov"},
  {t:"Non-repudiation",d:"The assurance that someone cannot deny having performed an action — e.g. digital signatures prove who sent a message.",cat:"general"},
  {t:"NTLM",d:"NT LAN Manager — an older Microsoft authentication protocol vulnerable to pass-the-hash attacks.",cat:"general"},
  {t:"OCSP",d:"Online Certificate Status Protocol — a real-time alternative to CRLs for checking whether a digital certificate has been revoked.",cat:"general"},
  {t:"On-path attack",d:"Formerly called MITM. An attacker positions themselves between two parties to intercept or alter their traffic.",cat:"threats"},
  {t:"OPSEC",d:"Operational Security — the process of identifying and protecting sensitive information that could be useful to an adversary.",cat:"ops"},
  {t:"OSINT",d:"Open Source Intelligence — gathering information about a target from publicly available sources such as social media and public records.",cat:"threats"},
  {t:"OTP",d:"One-Time Password — a password valid for only one login session or short time period.",cat:"general"},
  {t:"PaaS",d:"Platform as a Service — cloud model where the provider manages the OS and runtime; you manage just your applications and data.",cat:"arch"},
  {t:"PAM",d:"Privileged Access Management — tools that control, monitor, and audit access to privileged accounts like admin accounts.",cat:"general"},
  {t:"PAP",d:"Password Authentication Protocol — an older, insecure authentication method that sends passwords in plain text.",cat:"general"},
  {t:"PBQ",d:"Performance-Based Question — an exam question type where you interact with a simulated environment rather than choosing from a list.",cat:"general"},
  {t:"PCI DSS",d:"Payment Card Industry Data Security Standard — requirements for organisations that handle credit card data.",cat:"gov"},
  {t:"Pen test",d:"Penetration testing — an authorised simulated attack on a system to find vulnerabilities before real attackers do.",cat:"ops"},
  {t:"PGP",d:"Pretty Good Privacy — an encryption program used for securing emails and files using public-key cryptography.",cat:"general"},
  {t:"Pharming",d:"An attack that redirects users from a legitimate website to a fake one, often by corrupting DNS records.",cat:"threats"},
  {t:"PHI",d:"Protected Health Information — any health data tied to an individual that is protected under HIPAA.",cat:"gov"},
  {t:"Phishing",d:"A social engineering attack delivered via email that tricks victims into clicking malicious links or revealing credentials.",cat:"threats"},
  {t:"PII",d:"Personally Identifiable Information — any data that can identify a specific individual such as name, SSN, or email.",cat:"gov"},
  {t:"PKI",d:"Public Key Infrastructure — the system of certificates, CAs, and policies used to create, manage, and verify digital identities.",cat:"general"},
  {t:"Privilege escalation",d:"When an attacker gains higher-level access than originally granted — e.g. a regular user obtaining admin rights.",cat:"threats"},
  {t:"RADIUS",d:"Remote Authentication Dial-In User Service — a protocol used to centralise authentication for network access.",cat:"arch"},
  {t:"Rainbow table",d:"A precomputed table of hash values used to crack passwords. Salting defeats rainbow table attacks.",cat:"threats"},
  {t:"Ransomware",d:"Malware that encrypts a victim's files and demands payment in exchange for the decryption key.",cat:"threats"},
  {t:"RBAC",d:"Role-Based Access Control — users are assigned roles, and roles are granted permissions.",cat:"general"},
  {t:"RDP",d:"Remote Desktop Protocol — a Microsoft protocol for remote access to a Windows desktop. A common attack target if exposed to the internet.",cat:"arch"},
  {t:"Risk",d:"The likelihood that a threat will exploit a vulnerability multiplied by the impact. Risk = Threat × Vulnerability × Impact.",cat:"gov"},
  {t:"RoE",d:"Rules of Engagement — a document that defines the scope and limitations of a penetration test.",cat:"ops"},
  {t:"Rootkit",d:"Malware that hides deep in the operating system and gives an attacker persistent, stealthy admin-level access.",cat:"threats"},
  {t:"RPO",d:"Recovery Point Objective — the maximum acceptable amount of data loss measured in time.",cat:"gov"},
  {t:"RSA",d:"Rivest–Shamir–Adleman — a widely used asymmetric encryption algorithm based on factoring large prime numbers.",cat:"general"},
  {t:"RTO",d:"Recovery Time Objective — the maximum acceptable time to restore a system after an incident.",cat:"gov"},
  {t:"S/MIME",d:"Secure/Multipurpose Internet Mail Extensions — a standard for encrypting and digitally signing email messages.",cat:"general"},
  {t:"SaaS",d:"Software as a Service — cloud model where a fully managed application is delivered over the internet.",cat:"arch"},
  {t:"Salting",d:"Adding random data to a password before hashing it, so identical passwords produce different hashes.",cat:"general"},
  {t:"SAML",d:"Security Assertion Markup Language — an XML-based standard for exchanging authentication data, commonly used for SSO.",cat:"general"},
  {t:"Sandbox",d:"An isolated environment used to safely run and analyse potentially malicious code without risking the main system.",cat:"ops"},
  {t:"SIEM",d:"Security Information and Event Management — a platform that collects and analyses log data to detect threats in real time.",cat:"ops"},
  {t:"SLA",d:"Service Level Agreement — a contract defining expected service levels such as uptime guarantees.",cat:"gov"},
  {t:"SMB",d:"Server Message Block — a protocol for file and printer sharing on Windows networks. Exploited by WannaCry ransomware.",cat:"arch"},
  {t:"Smishing",d:"SMS phishing — a social engineering attack delivered via text message.",cat:"threats"},
  {t:"SNMP",d:"Simple Network Management Protocol — used to monitor network devices. Older versions transmit data without encryption.",cat:"arch"},
  {t:"SOAR",d:"Security Orchestration, Automation, and Response — automates repetitive security tasks and coordinates incident response.",cat:"ops"},
  {t:"SOC",d:"Security Operations Centre — a team that monitors, detects, and responds to cybersecurity threats around the clock.",cat:"ops"},
  {t:"SOX",d:"Sarbanes-Oxley Act — US law requiring financial companies to maintain accurate records and protect financial data.",cat:"gov"},
  {t:"Spyware",d:"Malware that secretly monitors and collects information about a user's activity without their knowledge.",cat:"threats"},
  {t:"SQL injection",d:"An attack where malicious SQL code is inserted into an input field to manipulate a database.",cat:"threats"},
  {t:"SSH",d:"Secure Shell — an encrypted protocol for secure remote access to servers using port 22. Replaced Telnet.",cat:"arch"},
  {t:"SSL",d:"Secure Sockets Layer — the predecessor to TLS for encrypting web communications. Now deprecated.",cat:"general"},
  {t:"SSO",d:"Single Sign-On — allows a user to authenticate once and access multiple applications without logging in again.",cat:"general"},
  {t:"Steganography",d:"Hiding secret data within ordinary files like images or audio so the hidden data is not obvious.",cat:"threats"},
  {t:"TACACS+",d:"Terminal Access Controller Access Control System Plus — Cisco's alternative to RADIUS with stronger encryption.",cat:"arch"},
  {t:"Telnet",d:"An older remote access protocol that transmits all data including passwords in plain text. Replaced by SSH.",cat:"arch"},
  {t:"TLS",d:"Transport Layer Security — the current standard for encrypting data in transit (e.g. HTTPS). Replaced SSL.",cat:"general"},
  {t:"TOTP",d:"Time-based One-Time Password — a one-time password that changes every 30 seconds. Used in authenticator apps.",cat:"general"},
  {t:"TPM",d:"Trusted Platform Module — a hardware chip that stores cryptographic keys and supports features like BitLocker.",cat:"arch"},
  {t:"Trojan",d:"Malware disguised as legitimate software that opens a backdoor for the attacker but does not self-replicate.",cat:"threats"},
  {t:"TTP",d:"Tactics, Techniques, and Procedures — the behaviour patterns used by threat actors to identify attackers.",cat:"threats"},
  {t:"UEBA",d:"User and Entity Behaviour Analytics — uses machine learning to detect anomalous behaviour by users or devices.",cat:"ops"},
  {t:"UPS",d:"Uninterruptible Power Supply — a backup battery system that keeps equipment running during a power outage.",cat:"arch"},
  {t:"URL hijacking",d:"Also called typosquatting — registering misspelled domain names to trick users into visiting fake sites.",cat:"threats"},
  {t:"UTM",d:"Unified Threat Management — a single security appliance combining firewall, IDS/IPS, antivirus, and more.",cat:"arch"},
  {t:"VLAN",d:"Virtual Local Area Network — logically segments a physical network into separate zones, improving security.",cat:"arch"},
  {t:"VM",d:"Virtual Machine — software that emulates a complete computer running inside another computer.",cat:"arch"},
  {t:"VPN",d:"Virtual Private Network — an encrypted tunnel over the internet that makes it appear as though you're on a private network.",cat:"arch"},
  {t:"Vishing",d:"Voice phishing — a social engineering attack conducted over phone calls to trick victims into revealing information.",cat:"threats"},
  {t:"WAF",d:"Web Application Firewall — filters HTTP traffic to protect web applications from attacks like SQL injection and XSS.",cat:"arch"},
  {t:"WEP",d:"Wired Equivalent Privacy — an old, now broken Wi-Fi security protocol. Replaced by WPA2/WPA3.",cat:"threats"},
  {t:"Whaling",d:"A type of phishing that specifically targets high-profile individuals such as executives or board members.",cat:"threats"},
  {t:"Worm",d:"Self-replicating malware that spreads across networks without user interaction.",cat:"threats"},
  {t:"WPA2",d:"Wi-Fi Protected Access 2 — the most common wireless security standard using AES encryption.",cat:"arch"},
  {t:"WPA3",d:"Wi-Fi Protected Access 3 — the latest wireless security standard with stronger encryption and better password protection.",cat:"arch"},
  {t:"XSS",d:"Cross-Site Scripting — an attack where malicious scripts are injected into trusted websites and executed in a victim's browser.",cat:"threats"},
  {t:"Zero day",d:"A vulnerability unknown to the software vendor with no patch available. Extremely valuable to attackers.",cat:"threats"},
  {t:"Zero trust",d:"A security model that assumes no user or device should be trusted by default. Every access request must be verified.",cat:"arch"},
];

const DOMAIN_META = {
  general: { label: "General concepts",       badge: "badge-general", qd: "qd-general" },
  threats: { label: "Threats & attacks",      badge: "badge-threats", qd: "qd-threats" },
  arch:    { label: "Architecture",           badge: "badge-arch",    qd: "qd-arch"    },
  ops:     { label: "Operations",             badge: "badge-ops",     qd: "qd-ops"     },
  gov:     { label: "Governance & compliance",badge: "badge-gov",     qd: "qd-gov"     },
};
